const:
  foo: bar
packages:
- name: helloworld
  type: generic
  ephemeral: true
  config:
    commands:
    - ["echo", "hello world"]
- name: app
  type: go
  srcs:
  - "**/*.go"
  - go.mod
  - go.sum
  deps:
  - :helloworld
  argdeps:
  - version
  prep:
  - ["echo", "hello prep"]
  config:
    dontTest: true
    buildArgs:
    - -ldflags
    - -X main.version=${version}
    library: false
