packages:
    - name: app
      type: go
      srcs:
        - go.mod
        - go.sum
        - "**/*.go"
      env:
        - CGO_ENABLED=0
      deps:
        - //:app
      config:
        packaging: app
