tasks:
  install-deps:
    name: Install Go Dependencies
    description: Download and cache Go module dependencies
    command: |
      echo "Installing Go dependencies..."
      go mod download
      echo "Go dependencies installed successfully"
    triggeredBy:
      - postDevcontainerStart

  build-leeway:
    name: Build Leeway Application
    description: Build the main leeway application
    command: |
      echo "Building leeway application..."
      go build -o bin/leeway .
      echo "Leeway application built successfully"
    dependsOn:
      - install-deps

  test:
    name: Run Tests
    description: Run Go tests for the project
    command: |
      echo "Running tests..."
      go test ./...
      echo "Tests completed"
    dependsOn:
      - install-deps
    triggeredBy:
      - manual

  lint:
    name: Run Linter
    description: Run golangci-lint on the codebase
    command: |
      echo "Running linter..."
      if command -v golangci-lint >/dev/null 2>&1; then
        golangci-lint run
      else
        echo "golangci-lint not available, skipping lint check"
      fi
      echo "Linting completed"
    dependsOn:
      - install-deps
    triggeredBy:
      - manual

  setup-claude-code-key:
    name: Key for Claude Code
    command: |
      [ -f /opt/.anthropic_key.sh ] && {
        install -D -m 755 /opt/.anthropic_key.sh ~/.claude/.anthropic_key.sh
        result=$(cat ~/.claude/settings.json 2>/dev/null || echo "{}" | jq '.apiKeyHelper = "~/.claude/.anthropic_key.sh"') && echo "$result" > ~/.claude/settings.json || true
      } || true
    triggeredBy:
    - postEnvironmentStart